<?php 

if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array(
	'key' => 'group_639c33152d08f',
	'title' => 'Карточка товара',
	'fields' => array(
		array(
			'key' => 'field_63bff1c55f8a0',
			'label' => 'Описание',
			'name' => '',
			'type' => 'accordion',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'open' => 0,
			'multi_expand' => 0,
			'endpoint' => 0,
			'acfe_field_group_condition' => 0,
		),
		array(
			'key' => 'field_647f190633087',
			'label' => 'Текст',
			'name' => 'products_text',
			'type' => 'wysiwyg',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'acfe_field_group_condition' => 0,
			'tabs' => 'all',
			'toolbar' => 'full',
			'media_upload' => 1,
			'default_value' => '',
			'delay' => 0,
		),
		array(
			'key' => 'field_63bff1d95f8a1',
			'label' => 'Слайдер',
			'name' => 'products_slider',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'acfe_repeater_stylised_button' => 0,
			'collapsed' => '',
			'min' => 0,
			'max' => 0,
			'layout' => 'table',
			'button_label' => '',
			'acfe_field_group_condition' => 0,
			'sub_fields' => array(
				array(
					'key' => 'field_63bff1f65f8a3',
					'label' => 'Изображение',
					'name' => 'img',
					'type' => 'image',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'uploader' => '',
					'acfe_thumbnail' => 0,
					'return_format' => 'array',
					'preview_size' => 'full',
					'min_width' => '',
					'min_height' => '',
					'min_size' => '',
					'max_width' => '',
					'max_height' => '',
					'max_size' => '',
					'mime_types' => '',
					'acfe_field_group_condition' => 0,
					'library' => 'all',
				),
			),
		),
		array(
			'key' => 'field_639c334de0767',
			'label' => 'Характериситики препарата',
			'name' => '',
			'type' => 'accordion',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'open' => 0,
			'multi_expand' => 0,
			'endpoint' => 0,
			'acfe_field_group_condition' => 0,
		),
		array(
			'key' => 'field_639c3368e0768',
			'label' => 'Характериситики',
			'name' => 'product_chars',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'acfe_repeater_stylised_button' => 0,
			'collapsed' => '',
			'min' => 0,
			'max' => 0,
			'layout' => 'table',
			'button_label' => '',
			'acfe_field_group_condition' => 0,
			'sub_fields' => array(
				array(
					'key' => 'field_639c3391e0769',
					'label' => 'Строка',
					'name' => '',
					'type' => 'accordion',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'open' => 0,
					'multi_expand' => 0,
					'endpoint' => 0,
					'acfe_field_group_condition' => 0,
				),
				array(
					'key' => 'field_639c33a1e076a',
					'label' => 'Название',
					'name' => 'left',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
					'acfe_field_group_condition' => 0,
				),
				array(
					'key' => 'field_639c33aee076b',
					'label' => 'Значение',
					'name' => 'right',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
					'acfe_field_group_condition' => 0,
				),
			),
		),
		array(
			'key' => 'field_647f59fab70bd',
			'label' => 'Картинка',
			'name' => 'product_chars_img',
			'type' => 'image',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'uploader' => '',
			'acfe_thumbnail' => 0,
			'return_format' => 'array',
			'preview_size' => 'full',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
			'acfe_field_group_condition' => 0,
			'library' => 'all',
		),
		array(
			'key' => 'field_639c33cde076c',
			'label' => 'Показания',
			'name' => '',
			'type' => 'accordion',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'open' => 0,
			'multi_expand' => 0,
			'endpoint' => 0,
			'acfe_field_group_condition' => 0,
		),
		array(
			'key' => 'field_639c33e6e076d',
			'label' => 'Фото',
			'name' => 'testimony_image',
			'type' => 'image',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'uploader' => '',
			'acfe_thumbnail' => 0,
			'return_format' => 'url',
			'preview_size' => 'full',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
			'acfe_field_group_condition' => 0,
			'library' => 'all',
		),
		array(
			'key' => 'field_639c3436e076f',
			'label' => 'Текст',
			'name' => 'testimony_text',
			'type' => 'wysiwyg',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'tabs' => 'all',
			'toolbar' => 'full',
			'media_upload' => 1,
			'delay' => 0,
			'acfe_wysiwyg_height' => 300,
			'acfe_wysiwyg_min_height' => 300,
			'acfe_wysiwyg_max_height' => '',
			'acfe_wysiwyg_valid_elements' => '',
			'acfe_wysiwyg_custom_style' => '',
			'acfe_wysiwyg_disable_wp_style' => 0,
			'acfe_wysiwyg_autoresize' => 0,
			'acfe_wysiwyg_disable_resize' => 0,
			'acfe_wysiwyg_remove_path' => 0,
			'acfe_wysiwyg_menubar' => 0,
			'acfe_wysiwyg_transparent' => 0,
			'acfe_wysiwyg_merge_toolbar' => 0,
			'acfe_wysiwyg_custom_toolbar' => 0,
			'acfe_wysiwyg_toolbar_buttons' => array(
				'acfe_wysiwyg_toolbar_1' => array(
					'row-row-0' => array(
						'acfe_wysiwyg_toolbar_row' => 'formatselect',
					),
					'row-row-1' => array(
						'acfe_wysiwyg_toolbar_row' => 'bold',
					),
					'row-row-2' => array(
						'acfe_wysiwyg_toolbar_row' => 'italic',
					),
					'row-row-3' => array(
						'acfe_wysiwyg_toolbar_row' => 'bullist',
					),
					'row-row-4' => array(
						'acfe_wysiwyg_toolbar_row' => 'numlist',
					),
					'row-row-5' => array(
						'acfe_wysiwyg_toolbar_row' => 'blockquote',
					),
					'row-row-6' => array(
						'acfe_wysiwyg_toolbar_row' => 'alignleft',
					),
					'row-row-7' => array(
						'acfe_wysiwyg_toolbar_row' => 'aligncenter',
					),
					'row-row-8' => array(
						'acfe_wysiwyg_toolbar_row' => 'alignright',
					),
					'row-row-9' => array(
						'acfe_wysiwyg_toolbar_row' => 'link',
					),
					'row-row-10' => array(
						'acfe_wysiwyg_toolbar_row' => 'wp_more',
					),
					'row-row-11' => array(
						'acfe_wysiwyg_toolbar_row' => 'spellchecker',
					),
					'row-row-12' => array(
						'acfe_wysiwyg_toolbar_row' => 'fullscreen',
					),
					'row-row-13' => array(
						'acfe_wysiwyg_toolbar_row' => 'wp_adv',
					),
					'acfcloneindex' => array(
						'acfe_wysiwyg_toolbar_row' => '',
					),
				),
				'acfe_wysiwyg_toolbar_2' => array(
					'row-row-0' => array(
						'acfe_wysiwyg_toolbar_row' => 'strikethrough',
					),
					'row-row-1' => array(
						'acfe_wysiwyg_toolbar_row' => 'hr',
					),
					'row-row-2' => array(
						'acfe_wysiwyg_toolbar_row' => 'forecolor',
					),
					'row-row-3' => array(
						'acfe_wysiwyg_toolbar_row' => 'pastetext',
					),
					'row-row-4' => array(
						'acfe_wysiwyg_toolbar_row' => 'removeformat',
					),
					'row-row-5' => array(
						'acfe_wysiwyg_toolbar_row' => 'charmap',
					),
					'row-row-6' => array(
						'acfe_wysiwyg_toolbar_row' => 'outdent',
					),
					'row-row-7' => array(
						'acfe_wysiwyg_toolbar_row' => 'indent',
					),
					'row-row-8' => array(
						'acfe_wysiwyg_toolbar_row' => 'undo',
					),
					'row-row-9' => array(
						'acfe_wysiwyg_toolbar_row' => 'redo',
					),
					'row-row-10' => array(
						'acfe_wysiwyg_toolbar_row' => 'wp_help',
					),
					'acfcloneindex' => array(
						'acfe_wysiwyg_toolbar_row' => '',
					),
				),
				'acfe_wysiwyg_toolbar_3' => array(
					'acfcloneindex' => array(
						'acfe_wysiwyg_toolbar_row' => '',
					),
				),
				'acfe_wysiwyg_toolbar_4' => array(
					'acfcloneindex' => array(
						'acfe_wysiwyg_toolbar_row' => '',
					),
				),
			),
			'acfe_field_group_condition' => 0,
		),
		array(
			'key' => 'field_639c466405307',
			'label' => 'Области и техника введения',
			'name' => '',
			'type' => 'accordion',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'open' => 0,
			'multi_expand' => 0,
			'endpoint' => 0,
			'acfe_field_group_condition' => 0,
		),
		array(
			'key' => 'field_64955b423b31a',
			'label' => 'Скрыть блок',
			'name' => 'injection_check',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => '',
			'default_value' => 0,
			'ui' => 0,
			'acfe_field_group_condition' => 0,
			'ui_on_text' => '',
			'ui_off_text' => '',
		),
		array(
			'key' => 'field_647f1de03b7d2',
			'label' => 'Заголовок(ОБЛАСТИ ВВЕДЕНИЯ)',
			'name' => 'injection_title',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'acfe_field_group_condition' => 0,
		),
		array(
			'key' => 'field_64abe59e90029',
			'label' => 'Картинка без обводки в разделе ОБЛАСТИ ВВЕДЕНИЯ',
			'name' => 'injection_full_img',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => '',
			'default_value' => 0,
			'ui' => 0,
			'acfe_field_group_condition' => 0,
			'ui_on_text' => '',
			'ui_off_text' => '',
		),
		array(
			'key' => 'field_639c469805309',
			'label' => 'ОБЛАСТИ ВВЕДЕНИЯ',
			'name' => 'injection',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'acfe_repeater_stylised_button' => 0,
			'collapsed' => '',
			'min' => 0,
			'max' => 0,
			'layout' => 'block',
			'button_label' => '',
			'acfe_field_group_condition' => 0,
			'sub_fields' => array(
				array(
					'key' => 'field_648066d92f87b',
					'label' => 'Контент',
					'name' => '',
					'type' => 'accordion',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'open' => 0,
					'multi_expand' => 0,
					'endpoint' => 0,
					'acfe_field_group_condition' => 0,
				),
				array(
					'key' => 'field_647f1d833b7d1',
					'label' => 'Картинка',
					'name' => 'img',
					'type' => 'image',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'uploader' => '',
					'acfe_thumbnail' => 0,
					'return_format' => 'array',
					'preview_size' => 'full',
					'min_width' => '',
					'min_height' => '',
					'min_size' => '',
					'max_width' => '',
					'max_height' => '',
					'max_size' => '',
					'mime_types' => '',
					'acfe_field_group_condition' => 0,
					'library' => 'all',
				),
				array(
					'key' => 'field_639c46d00530c',
					'label' => 'Текст',
					'name' => 'text',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'acfe_field_group_condition' => 0,
					'default_value' => '',
					'maxlength' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
				),
			),
		),
		array(
			'key' => 'field_647f4336acab9',
			'label' => 'Заголовок(КУРС ПРОЦЕДУР)',
			'name' => 'cource_title',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'acfe_field_group_condition' => 0,
		),
		array(
			'key' => 'field_647f43a4acaba',
			'label' => 'Текст(КУРС ПРОЦЕДУР)',
			'name' => 'cource_text',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'acfe_field_group_condition' => 0,
		),
		array(
			'key' => 'field_647f43c1acabb',
			'label' => 'Заголовок(ТЕХНИКА ВВЕДЕНИЯ)',
			'name' => 'technic_title',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'acfe_field_group_condition' => 0,
		),
		array(
			'key' => 'field_647f4464acabf',
			'label' => 'Картинка(ТЕХНИКА ВВЕДЕНИЯ)',
			'name' => 'technic_img',
			'type' => 'image',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'uploader' => '',
			'acfe_thumbnail' => 0,
			'return_format' => 'array',
			'preview_size' => 'medium',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
			'acfe_field_group_condition' => 0,
			'library' => 'all',
		),
		array(
			'key' => 'field_647f4488acac0',
			'label' => 'Текст(ТЕХНИКА ВВЕДЕНИЯ)',
			'name' => 'technic_text',
			'type' => 'wysiwyg',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'acfe_field_group_condition' => 0,
			'tabs' => 'all',
			'toolbar' => 'full',
			'media_upload' => 1,
			'default_value' => '',
			'delay' => 0,
		),
		array(
			'key' => 'field_63bff0ac5f89e',
			'label' => 'Видео',
			'name' => '',
			'type' => 'accordion',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'open' => 0,
			'multi_expand' => 0,
			'endpoint' => 0,
			'acfe_field_group_condition' => 0,
		),
		array(
			'key' => 'field_63bff85313d03',
			'label' => 'Превью',
			'name' => 'product_video_preview',
			'type' => 'image',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'uploader' => '',
			'acfe_thumbnail' => 0,
			'return_format' => 'url',
			'preview_size' => 'full',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
			'acfe_field_group_condition' => 0,
			'library' => 'all',
		),
		array(
			'key' => 'field_63bff19b5f89f',
			'label' => 'Видеофайл',
			'name' => 'product_video',
			'type' => 'file',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'uploader' => '',
			'return_format' => 'url',
			'min_size' => '',
			'max_size' => '',
			'mime_types' => '',
			'upload_folder' => '',
			'multiple' => 0,
			'max' => '',
			'acfe_field_group_condition' => 0,
			'library' => 'all',
		),
		array(
			'key' => 'field_639c46dc0530d',
			'label' => 'Преимущества',
			'name' => '',
			'type' => 'accordion',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'open' => 0,
			'multi_expand' => 0,
			'endpoint' => 0,
			'acfe_field_group_condition' => 0,
		),
		array(
			'key' => 'field_639c5a94cb51f',
			'label' => 'Подзаголовок',
			'name' => 'advantages_subtitle',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'acfe_field_group_condition' => 0,
		),
		array(
			'key' => 'field_639c46e80530e',
			'label' => 'Преимущества',
			'name' => 'advantages',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'acfe_repeater_stylised_button' => 0,
			'collapsed' => '',
			'min' => 0,
			'max' => 0,
			'layout' => 'table',
			'button_label' => '',
			'acfe_field_group_condition' => 0,
			'sub_fields' => array(
				array(
					'key' => 'field_639c46f90530f',
					'label' => 'Элемент преимущества',
					'name' => 'item',
					'type' => 'textarea',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'maxlength' => '',
					'rows' => '',
					'new_lines' => '',
					'acfe_textarea_code' => 0,
					'acfe_field_group_condition' => 0,
				),
			),
		),
		array(
			'key' => 'field_6480777fbed0f',
			'label' => 'РЕЗУЛЬТАТЫ',
			'name' => '',
			'type' => 'accordion',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'open' => 0,
			'multi_expand' => 0,
			'endpoint' => 0,
			'acfe_field_group_condition' => 0,
		),
		array(
			'key' => 'field_6480782cbed10',
			'label' => 'Результаты',
			'name' => 'result',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'acfe_repeater_stylised_button' => 0,
			'collapsed' => '',
			'min' => 0,
			'max' => 0,
			'layout' => 'table',
			'button_label' => '',
			'acfe_field_group_condition' => 0,
			'sub_fields' => array(
				array(
					'key' => 'field_64f07eb63cc49',
					'label' => 'Картинка',
					'name' => 'картинка',
					'type' => 'image',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '30',
						'class' => '',
						'id' => '',
					),
					'uploader' => '',
					'acfe_thumbnail' => 0,
					'return_format' => 'array',
					'preview_size' => 'medium',
					'min_width' => '',
					'min_height' => '',
					'min_size' => '',
					'max_width' => '',
					'max_height' => '',
					'max_size' => '',
					'mime_types' => '',
					'acfe_field_group_condition' => 0,
					'library' => 'all',
				),
				array(
					'key' => 'field_64f07eec3cc4a',
					'label' => 'Информация',
					'name' => 'информация',
					'type' => 'repeater',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'acfe_repeater_stylised_button' => 0,
					'collapsed' => '',
					'min' => 0,
					'max' => 0,
					'layout' => 'table',
					'button_label' => '',
					'acfe_field_group_condition' => 0,
					'sub_fields' => array(
						array(
							'key' => 'field_64f07ef83cc4b',
							'label' => 'Текст 1',
							'name' => 'текст_1',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '30',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
							'acfe_field_group_condition' => 0,
						),
						array(
							'key' => 'field_64f07f013cc4c',
							'label' => 'Текст 2',
							'name' => 'текст_2',
							'type' => 'textarea',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '70',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'maxlength' => '',
							'rows' => 4,
							'new_lines' => 'br',
							'acfe_textarea_code' => 0,
							'acfe_field_group_condition' => 0,
						),
					),
				),
			),
		),
		array(
			'key' => 'field_639c4d3bffb30',
			'label' => 'Цвета товара',
			'name' => '',
			'type' => 'accordion',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'open' => 0,
			'multi_expand' => 0,
			'endpoint' => 0,
			'acfe_field_group_condition' => 0,
		),
		array(
			'key' => 'field_639c4d30ffb2f',
			'label' => 'Код основного цвета',
			'name' => 'product_color',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'acfe_field_group_condition' => 0,
		),
		array(
			'key' => 'field_64f0681db2d51',
			'label' => 'Инструкция',
			'name' => '',
			'type' => 'accordion',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'open' => 0,
			'multi_expand' => 0,
			'endpoint' => 0,
			'acfe_field_group_condition' => 0,
		),
		array(
			'key' => 'field_64f0682cb2d52',
			'label' => 'Инструкция',
			'name' => 'инструкция',
			'type' => 'file',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'uploader' => '',
			'return_format' => 'url',
			'min_size' => '',
			'max_size' => '',
			'mime_types' => '',
			'upload_folder' => '',
			'multiple' => 0,
			'max' => '',
			'acfe_field_group_condition' => 0,
			'library' => 'all',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'drug',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'left',
	'instruction_placement' => 'label',
	'hide_on_screen' => array(
		0 => 'the_content',
	),
	'active' => true,
	'description' => '',
	'show_in_rest' => 0,
	'acfe_autosync' => array(
		0 => 'php',
		1 => 'json',
	),
	'acfe_form' => 0,
	'acfe_display_title' => '',
	'acfe_meta' => '',
	'acfe_note' => '',
	'modified' => 1698178046,
));

endif;